name: python-workshop
channels:
  - conda-forge
  - pytorch
dependencies:
  # Minimum:
  - python=3.10
  - pip
  # Machine learning using Pytorch:
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-lightning
  # Standard scientific:
  - jupyterlab
  - matplotlib
  - numba
  - numpy
  - openpyxl
  - pandas
  - pytables
  - scipy
  - sympy
