name: py-workshop
channels:
  - conda-forge
  - pytorch
dependencies:
  # Minimum:
  - python=3.10
  - pip
  # Machine learning using Pytorch:
  - pytorch
  - torchvision
  - torchaudio
  # Standard scientific:
  - pip:
    - jupyterlab
    - matplotlib
    - numba
    - numpy
    - pandas
    - scipy